import type { Metadata } from "next";
import { DMSansVN } from "./fonts/dm-sans-vn";
import { Itel } from "./fonts/itel";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${DMSansVN.variable} ${Itel.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
