import type { Metadata } from "next";
import { DMSansVN } from "./fonts/dm-sans-vn";
import { Itel } from "./fonts/itel";
import "./globals.css";
import { MainLayout } from "./layout/main-layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="dark">
      <body
        className={`${DMSansVN.variable} ${Itel.variable} antialiased`}
        suppressHydrationWarning
      >
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  );
}
